### ISSUE TITLE
Podspec limited to iOS 9

### ISSUE THREAD

**Issue by skrew** [Tallwave/Gliphy#4]
Hi, 
I just tested your (great) lib with iOS 8 and seem to works.
Please set the platform to iOS 8 instead of iOS 9.

Thanks

**Comment by swilliams** [comment]
Cool. I just assumed some of the Dynamic Type stuff was 9 only. Just had to change some of the text styles in the tests and example app. Version 0.2.1 was just pushed to cocoapods. See PR #5 for details.

Thanks!
